version: "3"
#usage: docker-compose up -d [ryu-controller, ryu-controller-alpine]  
#attach to shell: docker exec -it [ryu-controller, ryu-controller-alpine] [bash,sh]
services:
  ryu-controller:
    profiles: ["debian"]
    container_name: ryu-controller
    image: pgmconreg/sdn_ryu:bullseye
    expose:
      - 6633
      - 8080 #for webservers of topology
    ports: #<host port>:<container port>
      - "6633:6633"
      - "8080:8080"
    volumes: #/path/on/host:/path/on/container
      - "/home/${USER}/<desired_directory>:/home/${USER}/externals" #mount desired directory into container. ${USER} references local host user, not containers user
    tty: true

  ryu-controller-alpine:
    profiles: ["alpine"]
    extends: ryu-controller
    container_name: ryu-controller-alpine
    image: pgmconreg/sdn_ryu:alpine